[package]
name = "pk-librarian"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pk-core    = { workspace = true }
pk-store   = { workspace = true }
pk-watcher = { workspace = true }
tokio      = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
anyhow     = { workspace = true }
thiserror  = { workspace = true }
reqwest    = { workspace = true }
tracing    = { workspace = true }
chrono     = { workspace = true }
